### ISSUE TITLE
Auto-deploy master to pip

### ISSUE THREAD

**Issue by fwkoch** [3ptscience/properties#10]

**Comment by fwkoch** [comment]
(Per Rowan's request)

**Comment by bsmithyman** [comment]
I have some thoughts on this; maybe we could discuss? I think that things going to `PyPI` should probably be signed tags. Technically this is possible, and I can make it happen (tomorrow if we want), but we should know the connotations first.

**Comment by rowanc1** [comment]
Lets connect in the morning tomorrow (first thing my time).

**Comment by bsmithyman** [comment]
Added on `master`, commit c0a409b5b046ff1144499b7e2f7657e73df0b986

**Comment by fwkoch** [comment]
Cool! Can you tell me the implications of this? Is this auto-deploy a big deal, like if I have a minor change, should I be hesitant to merge it into master? Or can we just slip little changes in without worrying about it?

I guess at the very least this means we should be careful to increment the version number with every merge, huh?

**Comment by bsmithyman** [comment]
I think we should probably be pretty careful with our release cycle, especially on the open source projects (`properties` and `steno3dpy`). The auto-deploy in this case means that it is published to PyPI, the archive that `pip install steno3d` draws from. Unlike the web app, we can't fix things on the fly. If we have any bugs, that potentially gets installed on someone's computer and then not updated for quite a while; so the goal is to be at least somewhat afraid of pushing to `master`.

@rowanc1 can comment more, but I think he and I are mostly on the same page here. I am thinking we might want to turn on repository protections on `properties:master` and `steno3dpy:master`. I think we should have a similar branching strategy to what we're using on `steno3d` itself; that is to say that feature branches get PR'd onto `dev`, and `master` only gets PRs from `dev` in most cases.

One subtlety: if the version already exists, the deploy is a no-op (there will be a message in the Travis log saying that it isn't overwriting the existing `.tar.gz` file). So, to trigger the deploy behaviour we have to increment the version number. While it is technically possible to remove and re-upload a version, in practice it is a bad idea. This is also a good thing, since it means it is unlikely we will accidentally release a version.

**Comment by fwkoch** [comment]
Thanks for the thorough explanation! Sounds great.
