### ISSUE TITLE
Pickling doesn't work for GettableProperties

### ISSUE THREAD

**Issue by fwkoch** [3ptscience/properties#114]
Pickling can't load classes with GettableProperties since it directly tries to `setattr`.

**Comment by bsmithyman** [comment]
Hmm. Can they simply be excluded from the state?

**Comment by fwkoch** [comment]
I don't think so - We don't want to lose immutable attributes like UID, date created, etc. across pickling/unpickling.

**Comment by bsmithyman** [comment]
Right. Hmm.
It seems like this is hard to solve in general, since they are so flexible. However, Is there a way we could tag certain attributes to be included in the state? Right now we are not storing the whole class dict, but rather just the entries that correspond to the properties. Could we give `GettableProperty` instances an optional argument that specifies a state attribute to save / restore? When it hit a `GettableProperty`, it would omit it from processing, but include any state attributes that were specified...?

**Comment by fwkoch** [comment]
I don't think I understand what you mean by a state attribute - could you give an example?

-----

I was thinking something as simple as:
OLD
```
    def __setstate__(self, newstate):
        for key, val in iteritems(newstate):
            setattr(self, key, pickle.loads(val))
```
NEW
```
    def __setstate__(self, newstate):
        for key, val in iteritems(newstate):
            self._backend[key] = pickle.loads(val)
```
But then this piggy-backs onto some of the discussion in #113 about what sort of validation should happen on unpickling. With this, there would be none at all.

**Comment by bsmithyman** [comment]
Ah. Okay, a `GettableProperty` may be:
1) Fully specified somehow through the other properties
2) Specified somewhere else, e.g., with `_variable`, and then it is presenting an interface to it.

The latter is the case when dealing w/ things like the fixed `uuid` case. So, in case (1), we actually don't _want_ to try to unpack anything, because it is specified already from the rest of the state, and the `GettableProperty` doesn't allow setting. In case (2), we need to unpack something, but not the `GettableProperty` itself, and we don't know what. However, perhaps the `GettableProperty` itself can specify a list of attribute names like `_variable`, which are added to the state in its place, and then mapped back to the equivalent backing variables on load.

Currently, [only things that show up in the `_props` dictionary](https://github.com/3ptscience/properties/blob/dev/properties/base.py#L319) are actually stored, so otherwise there is no way that the `_variable` attribute is going to be pickled, right?

**Comment by fwkoch** [comment]
These are set directly to `_backend` with #123
