### ISSUE TITLE
suggestions for extending the types allowed 

### ISSUE THREAD

**Issue by lheagy** [3ptscience/properties#91]
I am working on implementing properties in the Regularization class of SimPEG. We have defined a custom class `Utils.Zero` that acts like a zero by overwriting the ufuncs (https://github.com/simpeg/simpeg/blob/master/SimPEG/Utils/matutils.py#L469). Since it is not inheriting from numpy and doesn't have a dtype, it is not recognized as an allowable type on validation.  
```
from SimPEG import Utils

class Regularization(properties.HasProperties): 
    mref = properties.Array("reference model", default=Utils.Zero())
```
Do you have a recommendation for how to have `Utils.Zero()` interpoerate with the `properties.Array`?

**Comment by fwkoch** [comment]
@lheagy - My initial suggestion is to do something like:

``` python
import properties
from SimPEG import Utils


class SimPEGArray(properties.Array):
    def validate(self, instance, value):
        if isinstance(value, (Utils.Zero, Utils.Identity)):
            return value
        return super(SimPEGArray, self).validate(instance, value)


class Regularization(properties.HasProperties): 
    mref = SimPEGArray("reference model", default=Utils.Zero)
```

That would allow `Zero` and `Identity` to pass validation, but validate everything else as an array. Is that along the lines of what you need?


(Also, as a side note, `default` values can be callable - you may want to use that for Utils.Zero (as I did above) so each instance of `Regularization` has its own instance of `Zero` rather than all sharing the same instance. Of course, maybe the latter behaviour is what you want.)

**Comment by lheagy** [comment]
Ah, cool, thanks @fwkoch! I like the default being callable as well :)
