### ISSUE TITLE
Expanding functionality to function variables.

### ISSUE THREAD

**Issue by grosenkj** [3ptscience/properties#97]
Is it possible to extend the functionality of `properties` to support function variables?

Something like this
```python
arg1 = properties.Float('Argument description', default=1.0, min=0.).as_argument()

def my_function(arg1):
    """
    Function description
    """
    # Argument description would be combined and
    # arg1 could be validated as with properties
    arg1.validite() 
    result = do_work_with_arg1
    return result
```
This would be really useful when you have the same variable/argument as an input in multiple functions in a library.

**Comment by fwkoch** [comment]
@grosenkj - This is a really nice idea. It is somewhat similar to the `Task` classes @bsmithyman put together; these expand `HasProperties` classes to contain a `__call__` method. You could do something similar, like so:

``` python
import properties

prop_a = properties.Integer('a')
prop_b = properties.Integer('b')

class _Adder(properties.HasProperties):
    """Add two ints"""
    int_a = prop_a
    int_b = prop_b
    
    def __call__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
        self.validate()
        return self.int_a+self.int_b
    
class _Subber(properties.HasProperties):
    """Subtract two ints"""
    int_a = prop_a
    int_b = prop_b
    
    def __call__(self, int_a, int_b):
        self.int_a = int_a
        self.int_b = int_b
        self.validate()
        return self.int_a-self.int_b
    
add = _Adder()
subtract = _Subber()
```
Then you can use these like functions:
<img width="540" alt="screen shot 2016-11-25 at 9 53 27 am" src="https://cloud.githubusercontent.com/assets/9453731/20631648/0f34c110-b2f5-11e6-80b1-041edc32bada.png">

A few things:
- The properties can be defined outside the classes and shared.
- The `__call__` methods must set the values to `self` and `validate`.
- You can deal with `kwargs` (eg `_Adder`) or explicit arguments (eg `_Subber`) in `__call__`.
- The documentation is generated from the `class`, not the `__call__` function. That means variable names correspond to the properties, not the call signature of `__call__`. I think that is not a problem as long as some care is taken when defining your functions.

The one additional thing `Task` does that this example does not is return a `HasProperties` `Result`. This means the output is also validated. Maybe you want that, maybe not...

Anyway, please let me know what you think of this. I'm curious if it meets your needs.

**Comment by fwkoch** [comment]
One more thing: Property order in the docs will be alphabetical unless specified otherwise with `_doc_order`. You can use this to ensure documentation is in the same order as input parameters.

``` python
class _Subber(properties.HasProperties):
    """Subtract two ints"""
    _doc_order = ['int_b', 'int_a']
    int_a = prop_a
    int_b = prop_b
    
    def __call__(self, int_b, int_a):
        self.int_a = int_a
        self.int_b = int_b
        self.validate()
        return self.int_b-self.int_a
    
subtract = _Subber()
```

<img width="528" alt="screen shot 2016-11-25 at 12 40 03 pm" src="https://cloud.githubusercontent.com/assets/9453731/20634286/5487c34a-b30c-11e6-9d8b-cce9af432ab7.png">

**Comment by fwkoch** [comment]
@grosenkj - Last thing for now: You can also use `Property` validation independently of `HasProperties` classes:

``` python
import properties

prop_a = properties.Integer('a')
prop_b = properties.Integer('b')

def subtract(a, b):
    prop_a.validate(None, a)
    prop_b.validate(None, b)
    return a-b
```

<img width="275" alt="screen shot 2016-11-25 at 12 45 36 pm" src="https://cloud.githubusercontent.com/assets/9453731/20634348/1e41fe4e-b30d-11e6-8708-5d934c46baa3.png">

The `None` parameter is the `HasProperties` instance, which doesn't exist in this case. The error message doesn't look great since it tries to get info from that instance:

<img width="1024" alt="screen shot 2016-11-25 at 12 46 39 pm" src="https://cloud.githubusercontent.com/assets/9453731/20634358/41664f4c-b30d-11e6-8943-4ad73d8344a8.png">

This could possibly be improved with some monkeying around.

Also, there are no auto-generated docs, which may be a problem.

**Comment by grosenkj** [comment]
@fwkoch - Thanks for all these suggestions, I will be able to use some of these thought they aren't exactly do what I was thinking of. But then I again, I am not sure if it is at all possible to do pre-define function arguments and have the doc_str auto-generate and have validation happen in the background. I will continue exploring. 

Thank you very much for your time and help.
